name: Deploy Slidev
on:
  push:
    branches: [ main ] # Eğer ana dalın ismi 'master' ise master yaz
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build -- --base /${{ github.event.repository.name }}/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        id: deployment